Month 8/step 1
nordpage/react-stellar-burger pull request #3
Opened 2023-08-22 18:58 UTC by nordpage

2023-08-22 19:48 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали возможность добавления в конструктор ингредиентов
- Использовали `useMemo`
- В контекст обернуты только те компоненты, что будут его использовать

Необходимо исправить:
- Модальное окно должно закрываться нажатием на подлоку - ModalOverlay.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-22 19:48 UTC, andryxxa93 commented on src/components/main/main.js
> +                <IngredientsContext.Provider value={{data: data, onClick: onItemClick}}>
**Можно лучше**

такая запись значения контекста приводит к тому, что при каждом рендере App даже не связанным с изменением значения контекста будет создаватсья новый объект и передаваться новое значение контекста, это приведет к перерендеру всех компонентов использующих контекст

Нужно обернуть создание объекта в useMemo, как показано в этой статье https://hswolff.com/blog/how-to-usecontext-with-usereducer/ в разделе Performance Concerns

2023-08-22 19:48 UTC, andryxxa93 commented on src/components/main/main.js
> +    const onItemClick = (item, counter) =>{
**Можно лучше**
Функцию, которую вы передаёте через контекст лучше оборачивать в `useCallback`

2023-08-23 05:38 UTC, nordpage commented on src/components/main/main.js
> +    const onItemClick = (item, counter) =>{
спасибо за идею, исправлю чуть по-позже))

2023-08-23 05:39 UTC, nordpage commented on src/components/main/main.js
> +                <IngredientsContext.Provider value={{data: data, onClick: onItemClick}}>
Спасибо! Нужно разобраться с этой темой и поправлю в step8-2

2023-08-23 05:48 UTC, andryxxa93 commented
**Необходимо исправить**
- Сейчас даже при нажатии на саму карточку в модальном окне - происходит закрытие. Дело в том, что вы повесили onClick закрытия на ModalOverlay при этом обернув им всю модалку. У ModalOverlay не должно быть `children` это просто подложка.

2023-08-23 11:16 UTC, andryxxa93 commented
**Необходимо исправить**
- По заданию в проекте должны быть два компонента `Modal` и `ModalOverlay`. Вам не следовало убирать ModalOverlay из Modal - он должен там быть, просто не следует в него ничего оборачивать. 

Должно оно быть примерно так


```js
 return ReactDOM.createPortal(
    <>
      <div className={styles.modal}>
        <div className={styles.header}>
          <h3 className={`${styles.title} text text_type_main-large`}>
            {title}
          </h3>
          <button className={styles.button} type="button">
            <CloseIcon type="primary" onClick={onClose} />
          </button>
        </div>
        <div className={styles.content}>{children}</div>
      </div>
      <ModalOverlay onClick={onClose} />
    </>,
    modalRoot as HTMLDivElement
```

2023-08-23 12:32 UTC, andryxxa93 reviewed
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-24 08:25 UTC, merged